### ISSUE TITLE
Fix PRS bug

### ISSUE THREAD

**Issue by davidbrownza** [RUBi-ZA/MD-TASK#16]
* Let PRS script filter for CA an C - currently only filters for CA
* Updated documentation
  * Input files should be reduced to CA atoms
  * Co-ordinate files should be in .xyz format, not PDB

**Comment by oliserand** [comment]
PRS has been been simplified to use PDB files directly as initial topology and final conformation. Including C atoms may confuse the parsing of protein atoms in protein complexes containing non-protein C atoms. If necessary, this can be re-opened.
