### ISSUE TITLE
Network contact map

### ISSUE THREAD

**Issue by Leishem** [RUBi-ZA/MD-TASK#23]
Hi I was trying to generate a network contact map for the wild type and mutant protein (THR53 to ALA53).
For the wild type the contact map is fine and THR53 is in the center of the map, however, for the mutant ALA53, it is not in the center of the map instead the next residue ARG54 is in the center. Please help!

**Comment by oliserand** [comment]
Hi Leishem,
I'm only found your comment now. Did you find the reason for the issue? Any chance there was an additional residue (such as a ligand) placed before the mutation?
Kind regards.

**Comment by Leishem** [comment]
Hi
Thanks for the reply
I have solved the issue, there was a problem in the pdb format.  After
rectifying that it works fine.

On 31-Jul-2018 2:51 PM, "olivier" <notifications@github.com> wrote:

Hi Leishem,
I'm only found your comment now. Did you find the reason for the issue? Any
chance there was an additional residue (such as a ligand) placed before the
mutation?
Kind regards.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/RUBi-ZA/MD-TASK/issues/23#issuecomment-409155037>, or mute
the thread

**Comment by oliserand** [comment]
I guess this thread can be closed now.
