### ISSUE TITLE
Dynamic Cross-Correlation

### ISSUE THREAD

**Issue by wrmartin** [RUBi-ZA/MD-TASK#26]
Hello,

When trying to calculate the cross-correlation matrix, I receive the following error: 

Traceback (most recent call last):
  File "/home/will/MD-TASK/calc_correlation.py", line 201, in <module>
    main(args)
  File "/home/will/MD-TASK/calc_correlation.py", line 150, in main
    correlation = correlate(traj_matrix)
  File "/home/will/MD-TASK/calc_correlation.py", line 84, in correlate
    jdelta = resJ - meanJ
ValueError: operands could not be broadcast together with shapes (404,3) (202,3) 

The trajectory and pdb worked fine for the network analysis (which is great, btw), and the example data generated the heat map appropriately.  Any ideas what the problem could be here?

**Comment by oliserand** [comment]
Hello. This was a bug that showed in the case of residues and residue numbers were identical across chains. This issue has been addressed in the MDM-TASK-web and MDM-TASK-dev branches.
