### ISSUE TITLE
Average Shortest path

### ISSUE THREAD

**Issue by shozebhaider** [RUBi-ZA/MD-TASK#27]
I am trying to calculate --calc-L. Initially I started with the example threshold of 7.0 But soon realised that in your documentation it mentions _**Note: for --calc-L to work, all nodes in the network must be accessible from all other nodes in the network. When this is not the case, an error will occur. Try increasing the distance threshold when this happens.**_

My protein is 70Ang from end to end. Now even if I give it a value of 70 it still gives me the error _**ERROR::type=general:frame=1:message='generator' object has no attribute '__getitem__'**_

Can you please advise on this ?

**Comment by oliserand** [comment]
Hi shozebhaider,

Thank you for using MD-TASK. A 7 angstrom cutoff is generally fine for
inferring residue contacts, but I'll have a look at your inputs. Can you
please send us your PDB topology, trajectory files together with the
commands used?

Kind regards,
Olivier

**Comment by shozebhaider** [comment]
Hi Oliver,

I have used the command: 

python2.7 calc_network.py --topology cpxd_short.pdb --threshold 7.0  --generate-plots --calc-L --discard-graphs cpxd_short.xtc

You can download the trajectory/pdb file from this link 
https://www.dropbox.com/s/3kghdn05po3d9nv/short.tar.bz2?dl=0

Many thanks.

**Comment by oliserand** [comment]
Dear shozebhaider,

I've successfully run the commands you sent, using the recommended virtual
environment. You might be using a different version of one of the
dependencies.
Please activate the virtual environment before using MD-TASK scripts. See
here
<https://md-task.readthedocs.io/en/latest/general.html#activating-the-virtual-environment>
for instructions.

Kind regards,
Olivier

**Comment by shozebhaider** [comment]
Many thanks. Got it to work.
