### ISSUE TITLE
Could not process multiple-chain PDB topology

### ISSUE THREAD

**Issue by zhenglz** [RUBi-ZA/MD-TASK#30]
I encountered the "dimer-error", input a dimer protein traj, output only contains one chain. I dig into the code, find the following line 32 (calc_correlation.py):

`res = atom.residue.resSeq`

Here this line could only obtain the res-sequence number in the PDB file, but if it is a homo-dimer protein, then the output correlation map would only contain the one chain. 
Then I did a test, I input a trajectory with 606 residues (two chains, each 303 residues), output correlation map only shows 303 residues. 

I would suggest change this line into:
`res = atom.residue.index`

Although this would fix the dimer-error mentioned above, the residue indices in the output png file need to be reordered to align with those in the topology pdb file.

**Comment by oliserand** [comment]
Thank you. This bug has been fixed in the MDM-TASK-web / MDM-TASK-dev branches.
