### ISSUE TITLE
while calculating shortest path : 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by cpayal** [RUBi-ZA/MD-TASK#42]
Hi

I am using MD-TASK to calculate the shortest path in my network with `--calc-L`, where I am seeing the following error:

`ERROR::type=general:frame=1:message='generator' object is not subscriptable` on each frame. 

BC calculation works fine. 

I am using the following command:

`calc_network.py --topology step4_prod.gro --threshold 7.0 --generate-plots --calc-L --step 100 --discard-graphs --lazy-load step4_prod.trr`

Thanks
Payal

**Comment by oliserand** [comment]
Hi @cpayal. Can you please tell us which branch you've used for the installation? At first glance, it looks like it could have something to do with the version of one of the libraries..
Thanks

**Comment by cpayal** [comment]
Hi @oliserand . My OS is Ubuntu 22.04 LTS. As directed I first installed the system dependencies;

`sudo apt-get install virtualenvwrapper python-dev libblas-dev liblapack-dev libatlas-base-dev gfortran libpng-dev libfreetype6-dev python-tk r-base`

and then :
`git clone https://github.com/RUBi-ZA/MD-TASK.git
cd MD-TASK`

python dependiencies:
`sh install.sh`

activated the environment and installed the R-package

**Comment by oliserand** [comment]
Hi @cpayal, apologies for the confusion. We would recommend the use of the mdm-task-web branch found here: https://github.com/RUBi-ZA/MD-TASK/tree/mdm-task-web . The one on the main branch has dependency conflicts, and will eventually be replaced by this branch: https://github.com/RUBi-ZA/MD-TASK/tree/md-task-python3.9 .

Regards,
Olivier

**Comment by cpayal** [comment]
Ok, thanks @oliserand ! Do you recommend https://github.com/RUBi-ZA/MD-TASK/tree/mdm-task-web or https://github.com/RUBi-ZA/MD-TASK/tree/md-task-python3.9 , in that case ?

Thanks,
Payal

**Comment by cpayal** [comment]
I just tried https://github.com/RUBi-ZA/MD-TASK/tree/mdm-task-web and still see the same error.

It occurs when I do --calc-L , while all other functions seem to work.

**Comment by oliserand** [comment]
Maybe check whether the environment from your previous installation is still being used. Conda should indicate that the mdmtaskweb environment is active. If that doesn't work, you can have a look at the [binder notebook](https://mybinder.org/v2/gh/RUBi-ZA/MD-TASK/mdmtask-dev?filepath=tutorial%2Fmdmtaskweb_tutorial.ipynb) for MDM-TASK-web and try your command on the example data. Otherwise you can email me a part of your trajectory, its coordinate file and the command you used. Thanks.

**Comment by cpayal** [comment]
Hi @oliserand 

I made a clean installation in a new conda environment this time, after which the path of the new MD-TASK installation was exported in my `~/.bashrc` file. I still see the problem. 

I tried with the files provided with the tutorial (data) and still see the same problem:
`!calc_network.py --topology /home/pchatterjee/bin/MD_TASK_new/MD-TASK/data/pr1.pdb --calc-L --step 1000 /home/pchatterjee/bin/MD_TASK_new/MD-TASK/data/pr1.trr
`

`INFO::Started at: 2022-10-27 10:53:00.599681
INFO::Calculating shortest paths...
ERROR::type=general:frame=1:message='generator' object is not subscriptable
INFO::Completed at: 2022-10-27 10:53:00.846119
INFO::- Total time: 0:00:00`

**Comment by oliserand** [comment]
Hi @cpayal,

It means that the issue is not with your data, but with the environment. Could you please confirm whether (1) you issued the command `deactivate` for pip, followed by `conda activate mdmtaskweb`;and (2) that the command `which python` shows you the path leading to the mdmtastweb environment. Thanks.

**Comment by cpayal** [comment]
Hi @oliserand 

I found the problem. I was exporting the $PATH variable to my MD-TASK directory, however, the tutorial you pointed me to uses scripts from within the$MD_TASK/src directory. Exporting the $MD_TASK/src as path, picked up the python files from that folder and worked fine! 
I think the python files in the main $MD_TASK directory were causing the issue. 

You could close this issue. Thanks for the help!

Payal
