### ISSUE TITLE
contact map images overlapping

### ISSUE THREAD

**Issue by cpayal** [RUBi-ZA/MD-TASK#44]
Hi

After using contact_map.py , although the target residue does have a few amino acids in contact, the generated image is overlapping, as shown below:

Present .png file looks like:

![image](https://user-images.githubusercontent.com/30321815/199107747-52bd9211-5e81-4174-811b-fbaf97856f35.png)

Could this be a specific library based issue ? I have used contact_map.py with the previous versions of MD-TASK, when the networks were generated using R as a pdf file and they worked fine for the same residues.

The pdf file with earlier versions looked like:
![image](https://user-images.githubusercontent.com/30321815/199108062-a5bc5265-ecba-4da8-bc90-13d2d486864f.png)

Thanks
Payal

**Comment by serge-andre** [comment]
Hello @cpayal. It's not impossible. But it might also be related to the labels present in the PDB coordinate file. If you used the previous coordinate file that contains an "X" as its chain label, then some character like that should appear on the right of that node. Is it possible to share a sample of your trajectory, along with the coordinate files? Thanks.

**Comment by oliserand** [comment]
Hi @cpayal. It's possible. But it might also be related to the labels present in the PDB coordinate file. If you used the previous one that contains an "X" as the chain label, then that character should appear on the right side of that node. Is it possible to share a sample of your trajectory, along with the coordinate file? Thanks.

**Comment by cpayal** [comment]
Hi @oliserand
I had named my chain as B, before running the calculation, which is why we see a jumbled "VAL617.B" in the overlapped image. 
Attached is a sample pdb and trajectory. 
[sample_files_contactmap.zip](https://github.com/RUBi-ZA/MD-TASK/files/9911187/sample_files_contactmap.zip)

**Comment by oliserand** [comment]
Hi @cpayal, the zip file is empty. Can you please send it once more. Thanks.

**Comment by cpayal** [comment]
Sorry about that !
Attached:
[sample_files_contactmap.zip](https://github.com/RUBi-ZA/MD-TASK/files/9912269/sample_files_contactmap.zip)

Thanks

**Comment by oliserand** [comment]
Both the coordinate and trajectory files look OK, and run correctly. So, I think it has something to do with the libraries on your end. Please check that the conda environment is taking precedence over other any other pip environment or python installation you may have. 
Here's what I got using this:
 `./contact_map.py --topology sample_reduced.pdb --residue PHE617 --chain B sample_reduced.trr`
[results.zip](https://github.com/RUBi-ZA/MD-TASK/files/9912543/results.zip)

**Comment by cpayal** [comment]
Hi @oliserand 

Thanks for the test and suggestions. Yes, you were right, I had earlier installed networkx through pip, uninstalled it and reinstalled in my conda environment.

Thanks
Payal
