### ISSUE TITLE
PRS input files ????

### ISSUE THREAD

**Issue by Vasudha-pai** [RUBi-ZA/MD-TASK#52]
Hello,
I've found the MDM task tool very useful, however I had a query regarding the input files. 
In the mdm-task-web> mdmtaskweb_tutorial.ipynb the --final file was taken from the Protein data bank. however, in the MD task manual, it says to use the final pdb file of the target conformation. 
Can I please have clarity on what should be the input files while working with MDM task. is it a pdb file from the protein data bank or final md topology pdb file?

**Comment by oliserand** [comment]
Hi Vasudha,

Thanks for using MDM-TASK-web. The target conformation in PRS is one that
is homologous to the starting structure, but has a different conformation.
The two conformations need to have the same number of CA atoms. One
basically wants to know if you nudge each residue of a starting
conformation, how likely is the nudged protein resembling a certain target
conformation, assuming an underlying linear model of motion. It builds that 
model from an equilibrated portion of an MD trajectory. In the end,
you end up finding potential allosteric sites. You could read up more about
it here: https://pubs.acs.org/doi/10.1021/acs.jcim.6b00775#

Kind regards,
Olivier

**Comment by Vasudha-pai** [comment]
Thank you so much for your response Oliver. 
I took the first frame as my initial conformation and the last frame from the trajectory file as my final conformation. but I keep getting an error saying that the trajectory and topology files do not have the same number of atoms. 
but when I take the entire frames as my initial conformation I get the graph. So I was genuinely confused if I was doing it right. 
Thanks again!

**Comment by oliserand** [comment]
No problem. My best guess is that you might not have the same number of
atoms in your trajectory and the coordinate/topology file.
